2024/04/12 12:36:52 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "POST /api/users/login/ HTTP/1.1", upstream: "http://172.18.0.4:8000/api/users/login/", host: "127.0.0.1:8443", referrer: "https://localhost:8483/"
2024/04/12 13:02:18 [emerg] 1#1: host not found in upstream "frontend" in /etc/nginx/nginx.conf:19
2024/04/12 13:03:31 [emerg] 1#1: host not found in upstream "frontend" in /etc/nginx/nginx.conf:19
2024/04/12 13:04:59 [emerg] 1#1: host not found in upstream "frontend" in /etc/nginx/nginx.conf:19
2024/04/12 13:06:09 [emerg] 1#1: host not found in upstream "frontend" in /etc/nginx/nginx.conf:19
2024/04/12 13:10:10 [emerg] 1#1: host not found in upstream "frontend" in /etc/nginx/nginx.conf:19
2024/04/12 13:48:16 [emerg] 1#1: host not found in upstream "frontend" in /etc/nginx/nginx.conf:19
2024/04/12 13:55:27 [error] 29#29: *28 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /api/users/all/ HTTP/1.1", upstream: "http://172.18.0.4:8000/api/users/all/", host: "127.0.0.1:8443", referrer: "https://localhost:8483/"
2024/04/12 13:55:28 [error] 29#29: *28 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "OPTIONS /api/users/all/ HTTP/1.1", upstream: "http://172.18.0.4:8000/api/users/all/", host: "127.0.0.1:8443", referrer: "https://localhost:8483/"
2024/04/12 14:01:38 [error] 29#29: *26 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /api/users/all/ HTTP/1.1", upstream: "http://172.18.0.4:8000/api/users/all/", host: "127.0.0.1:8443", referrer: "https://localhost:8483/"
2024/04/12 14:11:09 [error] 29#29: *28 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /api/users/all/ HTTP/1.1", upstream: "http://172.18.0.4:8000/api/users/all/", host: "127.0.0.1:8443", referrer: "https://localhost:8483/"
2024/04/12 14:11:12 [error] 29#29: *28 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "OPTIONS /api/users/all/ HTTP/1.1", upstream: "http://172.18.0.4:8000/api/users/all/", host: "127.0.0.1:8443", referrer: "https://localhost:8483/"
2024/04/12 14:11:14 [error] 29#29: *28 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "OPTIONS /api/users/all/ HTTP/1.1", upstream: "http://172.18.0.4:8000/api/users/all/", host: "127.0.0.1:8443", referrer: "https://localhost:8483/"
2024/04/12 14:16:44 [emerg] 1#1: host not found in upstream "frontend" in /etc/nginx/nginx.conf:19
2024/04/12 14:22:17 [error] 29#29: *28 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /api/users/all/ HTTP/1.1", upstream: "http://172.18.0.4:8000/api/users/all/", host: "127.0.0.1:8443", referrer: "https://localhost:8483/"
2024/04/12 14:22:19 [error] 29#29: *28 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "OPTIONS /api/users/all/ HTTP/1.1", upstream: "http://172.18.0.4:8000/api/users/all/", host: "127.0.0.1:8443", referrer: "https://localhost:8483/"
2024/04/12 14:25:36 [error] 29#29: *4 client intended to send too large body: 100763656 bytes, client: 172.18.0.1, server: localhost, request: "POST /upload HTTP/1.1", host: "localhost:8483", referrer: "https://localhost:8483/profile"
2024/04/12 14:37:09 [error] 29#29: *28 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /api/users/all/ HTTP/1.1", upstream: "http://172.18.0.4:8000/api/users/all/", host: "127.0.0.1:8443", referrer: "https://localhost:8483/"
2024/04/12 14:56:49 [emerg] 1#1: host not found in upstream "frontend" in /etc/nginx/nginx.conf:19
2024/04/12 14:59:10 [error] 29#29: *27 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /api/users/all/ HTTP/1.1", upstream: "http://172.18.0.4:8000/api/users/all/", host: "127.0.0.1:8443", referrer: "https://localhost:8483/"
2024/04/12 14:59:11 [error] 29#29: *27 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "OPTIONS /api/users/all/ HTTP/1.1", upstream: "http://172.18.0.4:8000/api/users/all/", host: "127.0.0.1:8443", referrer: "https://localhost:8483/"
2024/04/12 15:11:06 [error] 29#29: *29 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /api/users/all/ HTTP/1.1", upstream: "http://172.18.0.4:8000/api/users/all/", host: "127.0.0.1:8443", referrer: "https://localhost:8483/"
2024/04/12 15:11:10 [error] 29#29: *29 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "OPTIONS /api/users/all/ HTTP/1.1", upstream: "http://172.18.0.4:8000/api/users/all/", host: "127.0.0.1:8443", referrer: "https://localhost:8483/"
